version: "3.9"
services:
  database:
    image: "mysql:8.0.32"
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  wordpress:
    image: "wordpress:6.1.1-apache"
    depends_on:
      - cache_server
      - database
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1 #デバッグモードにするためのフラグ
    ports:
      - 8080:80
    volumes:
      - ./wordpress/:/var/www/html